using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NutritionCalculator.Models
{
    public class Category
    {
        [Key] // this is a Primary Key field
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // specify that the field’s values will be generated by the database
        public int ID { get; set; }
        [StringLength(200)]
        [Required]
        public string Name { get; set; }
    }
}
